config/routes.rb
Rails.application.routes.draw do
  #get 'messages/message_text:text'

  get 'home/index'

  devise_for :users
  resources :users
  resources :homes
  resources :person2s
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :persons
 #get '/person', to: 'person#index'
  root to: "homes#index"
  get 'homes/savemessage'
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
    @users=User.all
    
  end
  def savemessage
    puts ">>>>>>>>>>>>>>>>>>>>>>>>>save message"
  end
  # GET /homes/1
  # GET /homes/1.json
  def show
    puts ">>>>>>>>>>>>>>>>>s show"
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.fetch(:home, {})
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_for(home) do |f| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<div class="container-fluid">

    <div class="row">
        <p id="notice"><%= notice %></p>
    </div>
    <div class="row ">
        <div class="col-md-offset-3 col-md-6">
           
        </div>
    </div>
    <div class="row">
        <div class="col-md-offset-10 col-md-2">
            <%=render "shared/users_list",users: @users%>
        </div>
    </div>
    
    <!--div class="row">
        <%= link_to 'New Home', new_home_path %>
    </div-->
</div>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>
dfgdfgfdgsg sdgfd gfdgfgsfd
<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/homes/show.js.erb
alert("ddsfaf afdsaf s")